// Generated by scripts/generate-article-covers.py; editorial covers take precedence.
export const ARTICLE_COVER_FALLBACKS = {
  "01899275-a950-45b7-922a-0e71a5e35b7a": "/assets/article-covers/01899275-a950-45b7-922a-0e71a5e35b7a.png",
  "fd7a55a3-7964-4c9f-82c5-2a741e3e278d": "/assets/article-covers/fd7a55a3-7964-4c9f-82c5-2a741e3e278d.png",
  "6d6b83d5-be1a-41da-b562-4d8e5f92596c": "/assets/article-covers/6d6b83d5-be1a-41da-b562-4d8e5f92596c.png",
  "56e0dfb5-e39c-433c-81c5-c9cc94a92ac7": "/assets/article-covers/56e0dfb5-e39c-433c-81c5-c9cc94a92ac7.png",
  "c3988698-cbb4-4cb2-87cf-78c174f7acf5": "/assets/article-covers/c3988698-cbb4-4cb2-87cf-78c174f7acf5.png",
  "d713e358-d198-49fb-8f46-e23c1ee60950": "/assets/article-covers/d713e358-d198-49fb-8f46-e23c1ee60950.png",
  "da67e138-ddc0-40ca-8176-ac5f1d88361b": "/assets/article-covers/da67e138-ddc0-40ca-8176-ac5f1d88361b.png",
  "e2a8244b-472a-4fca-8061-37fc8d42a036": "/assets/article-covers/e2a8244b-472a-4fca-8061-37fc8d42a036.png",
  "388d4355-ede6-422e-bb33-8d6761c1e680": "/assets/article-covers/388d4355-ede6-422e-bb33-8d6761c1e680.png",
  "5d0b5ece-dfa6-4359-bb9e-03d96294df25": "/assets/article-covers/5d0b5ece-dfa6-4359-bb9e-03d96294df25.png",
  "71fdb47a-eb17-4704-a13a-a82ce4be9362": "/assets/article-covers/71fdb47a-eb17-4704-a13a-a82ce4be9362.png",
  "7f822f92-b6cf-4a3c-963e-09eba2458af1": "/assets/article-covers/7f822f92-b6cf-4a3c-963e-09eba2458af1.png",
  "8eb62131-624e-4a12-a42c-11709b38eda1": "/assets/article-covers/8eb62131-624e-4a12-a42c-11709b38eda1.png",
  "c668f12a-49f3-4548-8672-d7f02f26f558": "/assets/article-covers/c668f12a-49f3-4548-8672-d7f02f26f558.png",
  "b1c54007-f429-49c0-a19f-0e4fc10ce12a": "/assets/article-covers/b1c54007-f429-49c0-a19f-0e4fc10ce12a.png"
}
