"""Generate Arabic title cards for published items without editorial covers.

Requires Pillow, arabic-reshaper and python-bidi. Existing cover images are
preferred at runtime; these local assets are fallbacks, not database edits.
"""
import json
from pathlib import Path
from urllib.request import urlopen

import arabic_reshaper
from bidi.algorithm import get_display
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'public' / 'assets' / 'article-covers'
OUTPUT.mkdir(parents=True, exist_ok=True)
with urlopen('https://esnads.net/api/publications', timeout=30) as response:
    publications = json.load(response)['publications']


def visual(text):
    return get_display(arabic_reshaper.reshape(text))


def wrap(text, font, draw, width):
    lines = []
    line = ''
    for word in text.split():
        candidate = f'{line} {word}'.strip()
        if line and draw.textlength(visual(candidate), font=font) > width:
            lines.append(line)
            line = word
        else:
            line = candidate
    if line:
        lines.append(line)
    return lines


fallbacks = {}
for publication in publications:
    if publication.get('cover_image') or publication.get('kind') == 'book':
        continue
    identifier = publication['id']
    if not all(character.isalnum() or character in '-_' for character in identifier):
        raise ValueError('Invalid publication ID')
    image = Image.new('RGB', (1200, 675), '#f7f3ed')
    draw = ImageDraw.Draw(image)
    draw.rectangle((1144, 0, 1200, 675), fill='#a52a30')
    draw.line((66, 122, 1085, 122), fill='#dbcec0', width=2)
    label_font = ImageFont.truetype('C:/Windows/Fonts/arial.ttf', 29)
    draw.text((1080, 59), visual('مركز إسناد للدراسات والأبحاث'),
              font=label_font, fill='#a52a30', anchor='ra')
    # Preserve the full publication title, rather than replacing it with a slogan.
    title = publication['title_ar']
    for size in range(54, 25, -2):
        title_font = ImageFont.truetype('C:/Windows/Fonts/arialbd.ttf', size)
        lines = wrap(title, title_font, draw, 1010)
        line_height = int(size * 1.55)
        if len(lines) * line_height <= 350:
            break
    start = 170 + (350 - len(lines) * line_height) // 2
    for line in lines:
        draw.text((1080, start), visual(line), font=title_font, fill='#29262a', anchor='ra')
        start += line_height
    draw.line((66, 562, 1085, 562), fill='#dbcec0', width=2)
    author = publication.get('author_ar') or 'مركز إسناد'
    author_font = ImageFont.truetype('C:/Windows/Fonts/arial.ttf', 27)
    for index, line in enumerate(wrap(author, author_font, draw, 1000)[:2]):
        draw.text((1080, 590 + index * 36), visual(line), font=author_font,
                  fill='#665b53', anchor='ra')
    image.save(OUTPUT / f'{identifier}.png', optimize=True)
    fallbacks[identifier] = f'/assets/article-covers/{identifier}.png'

(ROOT / 'src' / 'lib' / 'articleCoverFallbacks.js').write_text(
    '// Generated by scripts/generate-article-covers.py; editorial covers take precedence.\n'
    'export const ARTICLE_COVER_FALLBACKS = ' + json.dumps(fallbacks, indent=2) + '\n',
    encoding='utf-8',
)
print(f'Generated {len(fallbacks)} Arabic title-card covers.')
